// packages/react-ds/src/Button.tsx
import React from 'react';
import styles from '@ederusena/styles/src/components/Button.module.scss';

const Button = () => {
	return (
		<>
			<button
				className={styles.btn}
				onClick={() => alert('I am styled with CSS Modules')}
			>
				I am button 2 - Press Me
      </button>
		</>
	);
};
export default Button;

// packages/vue-ds/src/components/Button/Button.vue
<script lang='ts'>
import { Component, Vue } from "vue-property-decorator";

@Component
export default class MyButton extends Vue {}
</script>

<template>
  <button :class="$style.btn">I am button 2 - Press Me</button>
</template>

<style lang='scss' module>
@import "~@ederusena/styles/src/components/Button.module.scss";
</style>
